services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    container_name: innova-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      NUXT_HOST: ${NUXT_HOST}
      NUXT_PORT: ${NUXT_PORT}
      BACKEND_URL: ${BACKEND_URL}
      SERVER_API_BASE: ${SERVER_API_BASE}
      API_BASE: ${API_BASE}
      NUXT_PUBLIC_CLARITY_ID: ${NUXT_PUBLIC_CLARITY_ID}
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - frontend_node_modules:/app/node_modules

volumes:
  frontend_node_modules:
